### PR TITLE
Updates to get everything working

### PR DESCRIPTION
**Pull request by kozhin**
I use Docker to run Rails apps on my mac but I suppose that it is not necessary if working with foreman. The idea is:

1. Start rails server with foreman using the following sequence of actions: bundle install **then** yarn install **then** bundle exec foreman start. First two actions are required only once.
2. Open in browser http://localhost:3000 (I suggest to disable firewall)
3. Try to modify anything.

I don't see any errors in console and HMR works as expected.

Also it may be not necessary to switch from localhost to 0.0.0.0 but it's how this works with Docker.
I have nodejs 8.6.0 on board and yarn 1.1.0.

### CODE REVIEW

**Comment by haffla** [comment]
Thanks a lot. Unfortunately I still have the same issue. To be 100% sure: Can you change the text `Hello Vue!` and the browser updates? Changing the CSS works fine.

**Comment by kozhin** [comment]
Oh, now I see. Modification of this line 
` message: 'Hello Vue!'`
produces an error. I don't think it is related to webpacker.

**Comment by kozhin** [comment]
Update hello_vue.js to with the following:

```
import Vue from 'vue'
import App from '../app.vue'

document.addEventListener('DOMContentLoaded', () => {
  document.body.appendChild(document.createElement('hello'))
  const app = new Vue({
    render: (h) => h(App)
  }).$mount('hello')

  console.log(app)
})
```

This should work.

**Comment by kozhin** [comment]
You may find demo here: https://yadi.sk/i/lgIn1xQl3NcXPh

**Comment by haffla** [comment]
So I summarize: The only change it needed is this: https://github.com/haffla/rails5-vue/commit/3dcf829c8c1d46880a79b3ad31a09deaae3d692f

How could I be so blind? I'm working with Vue for a longer time now. I should have seen that there is something wrong the way `App` is passed to the constructor. I remember thinking that this might be a new shorthand haha

Thank you so much @kozhin. I already gave up 💃

**Comment by kozhin** [comment]
You are welcome :) Actually I'm not familiar with Vue but I had similar issue with React a long time ago... and never give up :)

**Pull request closed without merging**
